---
resources:
  App\Entity\ScreenLayout:
    attributes:
      output: App\Dto\ScreenLayout
    itemOperations:
      get:
        path: '/layouts/{id}'
        openapi_context:
          description: Retrieves a screen layout resource.
          summary: Retrieve a screen layout resource.
          operationId: get-v1-layouts-id
          tags:
            - Layouts
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              headers: { }
#      put: ~
#      delete: ~

    collectionOperations:
      get:
        path: '/layouts'
        openapi_context:
          description: Retrieve a collection of layouts resources.
          summary: Retrieves a collection of layouts resources.
          tags:
            - Layouts
          operationId: get-v1-layouts
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 10
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              headers: { }
#      post: ~
