---
resources:
  App\Entity\Tenant\Playlist:
    attributes:
      input: App\Dto\PlaylistInput
      output: App\Dto\Playlist
      normalization_context:
        datetime_format: 'Y-m-d\TH:i:s.v\Z'
    itemOperations:
      get:
        openapi_context:
          operationId: get-v1-playlist-id
          description: Retrieve a Playlist resource.
          summary: Retrieves a Playlist resource.
          tags:
            - Playlists
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              headers: { }

      put:
        openapi_context:
          description: Update a Playlist resource.
          summary: Update a Playlist resource.
          operationId: put-v1-playlist-id
          tags:
            - Playlists
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        openapi_context:
          description: Delete a Playlist resource.
          summary: Delete a Playlist resource.
          operationId: delete-v1-playlist-id
          tags:
            - Playlists
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

    collectionOperations:
      get:
        filters: ['entity.search_filter', 'entity.blameable_filter', 'entity.published.date_filter','entity.is.campaign.bool_filter', 'entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter', 'tenants.search_filter']
        openapi_context:
          operationId: get-v1-playlists
          description: Retrieves a collection of Playlist resources.
          summary: Retrieve a collection of Playlist resources.
          tags:
            - Playlists
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
          responses:
            '200':
              description: OK
              headers: { }

      post:
        openapi_context:
          operationId: create-v1-playlist
          description: Creates a Playlist resource.
          summary: Creates a Playlist resource.
          tags:
            - Playlists
