---
resources:
  App\Entity\Tenant\Screen:
    attributes:
      security: 'is_granted("ROLE_SCREEN") or is_granted("ROLE_ADMIN")'
      input: App\Dto\ScreenInput
      output: App\Dto\Screen
    itemOperations:
      get:
        openapi_context:
          operationId: get-screens-id
          description: Retrieves a Screen resource.
          summary: Retrieve a Screen resource.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              headers: { }

      put:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          description: Update a Screen resource.
          summary: Update a Screen resource.
          operationId: put-v1-screen-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          description: Delete a Screen resource.
          summary: Delete a Screen resource.
          operationId: delete-v1-screen-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

    collectionOperations:
      get:
        filters: ['entity.search.multiple.values.search_filter', 'entity.blameable_filter', 'entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter']
        openapi_context:
          operationId: get-v1-screens
          description: Retrieves a collection of Screen resources.
          summary: Retrieves a collection of Screen resources.
          tags:
            - Screens
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              headers: { }

      post:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          operationId: create-v1-screens
          description: Creates a Screen resource.
          summary: Creates a Screen resource.
          tags:
            - Screens

      getCampaignScreens:
        method: GET
        filters: ['entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter']
        path: '/campaigns/{id}/screens'
        controller: App\Controller\CampaignScreenGetController
        openapi_context:
          description: Get Screen resources on campaign.
          summary: Get Screen resources on campaign.
          operationId: get-v1-campaign-id-screen
          tags:
            - Playlists
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
