---
resources:
  App\Entity\Tenant\Theme:
    attributes:
      security: 'is_granted("ROLE_SCREEN") or is_granted("ROLE_ADMIN")'
      input: App\Dto\ThemeInput
      output: App\Dto\Theme
    itemOperations:
      get:
        openapi_context:
          description: Retrieves a Theme resource.
          summary: Retrieve a Theme resource.
          operationId: get-v1-theme-id
          tags:
            - Themes
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              headers: { }

      put:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          description: Update a Theme resource.
          summary: Update a Theme resource.
          operationId: put-v1-theme-id
          tags:
            - Themes
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          description: Delete a Theme resource.
          summary: Delete a Theme resource.
          operationId: delete-v1-theme-id
          tags:
            - Themes
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

    collectionOperations:
      get:
        filters: ['entity.search_filter', 'entity.blameable_filter', 'entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter']
        openapi_context:
          operationId: get-v1-themes
          description:  Retrieve a collection of Theme resources.
          summary:  Retrieve a collection of Theme resources.
          tags:
            - Themes
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              headers: { }

      post:
        security: 'is_granted("ROLE_ADMIN")'
        openapi_context:
          operationId: create-v1-themes
          description: Creates a Theme resource.
          summary: Creates a Theme resource.
          tags:
            - Themes
